# Generated by Django 3.2.9 on 2021-12-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRevyakoES', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
