# Generated by Django 3.2.9 on 2021-12-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRevyakoES', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amortization_costs',
            table='Amortization_costs',
        ),
        migrations.AlterModelTable(
            name='invoice_costs',
            table='Invoice_costs',
        ),
        migrations.AlterModelTable(
            name='labor_costs',
            table='Labor_costs',
        ),
        migrations.AlterModelTable(
            name='material_costs',
            table='Material_costs',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
