# Generated by Django 3.2.9 on 2021-12-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRevyakoES', '0003_auto_20211204_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='period',
            field=models.IntegerField(default=1),
        ),
    ]
