# Generated by Django 3.2.9 on 2022-03-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appRevyakoES', '0004_product_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='breakeven_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Точка безубыточности'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_on_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Рентабельность продаж'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='amortization_costs',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='amortization_costs',
            name='count_equipment',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='amortization_costs',
            name='equipment_name',
            field=models.CharField(max_length=100, verbose_name='Название оборудования'),
        ),
        migrations.AlterField(
            model_name='amortization_costs',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRevyakoES.product', verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='amortization_costs',
            name='service_life',
            field=models.IntegerField(verbose_name='Срок эксплуатации'),
        ),
        migrations.AlterField(
            model_name='amortization_costs',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='invoice_costs',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='invoice_costs',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='invoice_costs',
            name='invoice_name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='invoice_costs',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRevyakoES.product', verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='invoice_costs',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='labor_costs',
            name='deduction',
            field=models.IntegerField(verbose_name='Отчисления'),
        ),
        migrations.AlterField(
            model_name='labor_costs',
            name='number_of_people',
            field=models.IntegerField(verbose_name='Количество людей'),
        ),
        migrations.AlterField(
            model_name='labor_costs',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRevyakoES.product', verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='labor_costs',
            name='profession',
            field=models.CharField(max_length=100, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='labor_costs',
            name='salary',
            field=models.IntegerField(verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='labor_costs',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='material_costs',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='material_costs',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='material_costs',
            name='material_name',
            field=models.CharField(max_length=100, verbose_name='Название материала'),
        ),
        migrations.AlterField(
            model_name='material_costs',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRevyakoES.product', verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='material_costs',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='output_volume',
            field=models.IntegerField(verbose_name='Объём выпуска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='period',
            field=models.IntegerField(default=1, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Название продукции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRevyakoES.user', verbose_name='Пользователь'),
        ),
    ]
