# Generated by Django 3.2.9 on 2022-03-16 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appRevyakoES', '0005_auto_20220315_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortization_costs',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizations', to='appRevyakoES.product', verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='invoice_costs',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='appRevyakoES.product', verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='labor_costs',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labors', to='appRevyakoES.product', verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='material_costs',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='appRevyakoES.product', verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='return_on_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Рентабельность продаж (%)'),
        ),
    ]
