# Generated by Django 3.2.9 on 2022-03-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRevyakoES', '0006_auto_20220316_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена продажи'),
        ),
    ]
